# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Format, Lint, and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install
      - name: Format with isort and black
        run: |
          # Sort python imports
          poetry run isort .
          # Format python files
          poetry run black .
      - name: Lint with mypy, flake8, and pylint
        run: |
          poetry run mypy .
          # stop the build if there are Python syntax errors or undefined names
          poetry run flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # Uncomment after programs and tests are written
          # poetry run pylint .
      - name: Test with pytest
        run: |
          # Uncomment after programs and tests are written
          # poetry run pytest
